name: C++ Unit Tests

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build_and_test:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: lukka/get-cmake@latest
        with:
          useLocalCache: true
      
      - uses: actions/checkout@v4

      - name: Configure for tests
        run: cmake --preset testing

      - name: Build tests
        run: cmake --build --preset testing

      - name: Test
        run: ctest --preset testing

      - name: Configure for release
        run: cmake --preset release

      - name: Build release
        run: cmake --build --preset release

      - name: Install
        run: cmake --install build/release
        

